INFLUX_CSD_IP = "10.0.4.87"
INFLUX_CSD_PORT = "30703"
INFLUX_CSD_USERNAME = 'keti'
INFLUX_CSD_PASSWORD = 'ketilinux'
INFLUX_CSD_DB = "opencsd_management_platform"

INFLUX_SSD_IP = "10.0.4.85"

INSTANCE_METRIC_DB_HOST = "10.0.4.87"
INSTANCE_METRIC_DB_PORT = "30701"
INSTANCE_METRIC_DB_USER = 'keti' #구분 필요
INSTANCE_METRIC_DB_PASSWORD = 'ketilinux' #구분 필요
INSTANCE_METRIC_DB_NAME = "opencsd" #구분 필요

# mysql
PLATFORM_MANAGEMENT_DB_HOST = "10.0.4.87"
PLATFORM_MANAGEMENT_DB_PORT = 30704
PLATFORM_MANAGEMENT_DB_USER = 'keti' #구분 필요
PLATFORM_MANAGEMENT_DB_PASSWORD = 'ketilinux' #구분 필요
PLATFORM_MANAGEMENT_DB_NAME = 'management'

INSTANCE_MANAGEMENT_DB_HOST = "10.0.4.87"
INSTANCE_MANAGEMENT_DB_PORT = 30702 #구분 필요
INSTANCE_MANAGEMENT_DB_USER = 'keti' #구분 필요
INSTANCE_MANAGEMENT_DB_PASSWORD = 'ketilinux' #구분 필요
INSTANCE_MANAGEMENT_DB_NAME = 'opencsd' #구분 필요