apiVersion: v1
kind: Service
metadata:
  name: opencsd-web-workbench-g
  namespace: gluesys
  labels:
    name: opencsd-web-workbench-g
    namespace: gluesys
spec:
  type: NodePort
  ports:
    - port: 40803
      targetPort: 40803
      nodePort: 30803
      protocol: TCP
  selector:
    name: opencsd-web-workbench-g
    namespace: gluesys
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: gluesys
spec:
  podSelector:
    matchLabels:
      name: opencsd-web-workbench-g
  ingress:
    - from:
        - podSelector: {}