apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-web-workbench-g
  namespace: gluesys
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opencsd-web-workbench-g
      namespace: gluesys
  template:
    metadata:
      labels:
        name: opencsd-web-workbench-g
        namespace: gluesys
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-web-workbench
          image: ketidevit2/opencsd-web-workbench:v1.0
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: operation-node2
      tolerations:
      - key: "use"
        operator: "Equal"
        value: "no"
        effect: "NoSchedule"
